// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/arthurdotwork/bastion/internal/domain/authentication"
	mock "github.com/stretchr/testify/mock"
)

// NewAccessTokenStore creates a new instance of AccessTokenStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAccessTokenStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *AccessTokenStore {
	mock := &AccessTokenStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// AccessTokenStore is an autogenerated mock type for the AccessTokenStore type
type AccessTokenStore struct {
	mock.Mock
}

type AccessTokenStore_Expecter struct {
	mock *mock.Mock
}

func (_m *AccessTokenStore) EXPECT() *AccessTokenStore_Expecter {
	return &AccessTokenStore_Expecter{mock: &_m.Mock}
}

// CreateAccessToken provides a mock function for the type AccessTokenStore
func (_mock *AccessTokenStore) CreateAccessToken(ctx context.Context, token authentication.AccessToken) (authentication.AccessToken, error) {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for CreateAccessToken")
	}

	var r0 authentication.AccessToken
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, authentication.AccessToken) (authentication.AccessToken, error)); ok {
		return returnFunc(ctx, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, authentication.AccessToken) authentication.AccessToken); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Get(0).(authentication.AccessToken)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, authentication.AccessToken) error); ok {
		r1 = returnFunc(ctx, token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AccessTokenStore_CreateAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAccessToken'
type AccessTokenStore_CreateAccessToken_Call struct {
	*mock.Call
}

// CreateAccessToken is a helper method to define mock.On call
//   - ctx
//   - token
func (_e *AccessTokenStore_Expecter) CreateAccessToken(ctx interface{}, token interface{}) *AccessTokenStore_CreateAccessToken_Call {
	return &AccessTokenStore_CreateAccessToken_Call{Call: _e.mock.On("CreateAccessToken", ctx, token)}
}

func (_c *AccessTokenStore_CreateAccessToken_Call) Run(run func(ctx context.Context, token authentication.AccessToken)) *AccessTokenStore_CreateAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(authentication.AccessToken))
	})
	return _c
}

func (_c *AccessTokenStore_CreateAccessToken_Call) Return(accessToken authentication.AccessToken, err error) *AccessTokenStore_CreateAccessToken_Call {
	_c.Call.Return(accessToken, err)
	return _c
}

func (_c *AccessTokenStore_CreateAccessToken_Call) RunAndReturn(run func(ctx context.Context, token authentication.AccessToken) (authentication.AccessToken, error)) *AccessTokenStore_CreateAccessToken_Call {
	_c.Call.Return(run)
	return _c
}
