// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package queries

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	GetUUID(ctx context.Context) (uuid.UUID, error)
}

var _ Querier = (*Queries)(nil)
