// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: uuid.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const getUUID = `-- name: GetUUID :one
SELECT gen_random_uuid()
`

func (q *Queries) GetUUID(ctx context.Context) (uuid.UUID, error) {
	row := q.queryRow(ctx, q.getUUIDStmt, getUUID)
	var gen_random_uuid uuid.UUID
	err := row.Scan(&gen_random_uuid)
	return gen_random_uuid, err
}
