services:
  psql:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - psql_data:/var/lib/postgresql/data

  web:
    build:
      context: apps/web
    ports:
      - "3000:80"
    environment:
      APP_ENV: local

  srv:
    build:
      context: apps/srv
    ports:
      - "8080:8080"
    environment:
      DATABASE_HOST: psql
      GIN_MODE: release
    depends_on:
      - psql

volumes:
  psql_data:
    driver: local
