# https://taskfile.dev

version: '3'

tasks:
  lint:install:
    desc: Install the linter
    status:
      - golangci-lint version | grep "version 2.0.2"
    cmds:
      - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/HEAD/install.sh | sh -s -- -b $(go env GOPATH)/bin v2.0.2
  lint:
    desc: Run the linter
    deps:
      - lint:install
    cmds:
      - golangci-lint run --timeout 5m

  test:install:
    desc: Install the test runner
    status:
      - gotestsum version
    cmds:
      - go install gotest.tools/gotestsum@latest
  test:
    desc: Run the tests
    deps:
      - test:install
    cmds:
      - gotestsum --format pkgname-and-test-fails -- -race --count=1

  build:
    desc: Build the project
    cmds:
      - docker buildx build -t bastion:local .
