// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewHasher creates a new instance of Hasher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHasher(t interface {
	mock.TestingT
	Cleanup(func())
}) *Hasher {
	mock := &Hasher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Hasher is an autogenerated mock type for the Hasher type
type Hasher struct {
	mock.Mock
}

type Hasher_Expecter struct {
	mock *mock.Mock
}

func (_m *Hasher) EXPECT() *Hasher_Expecter {
	return &Hasher_Expecter{mock: &_m.Mock}
}

// Hash provides a mock function for the type Hasher
func (_mock *Hasher) Hash(ctx context.Context, password string) (string, error) {
	ret := _mock.Called(ctx, password)

	if len(ret) == 0 {
		panic("no return value specified for Hash")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, password)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, password)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Hasher_Hash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Hash'
type Hasher_Hash_Call struct {
	*mock.Call
}

// Hash is a helper method to define mock.On call
//   - ctx
//   - password
func (_e *Hasher_Expecter) Hash(ctx interface{}, password interface{}) *Hasher_Hash_Call {
	return &Hasher_Hash_Call{Call: _e.mock.On("Hash", ctx, password)}
}

func (_c *Hasher_Hash_Call) Run(run func(ctx context.Context, password string)) *Hasher_Hash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Hasher_Hash_Call) Return(s string, err error) *Hasher_Hash_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *Hasher_Hash_Call) RunAndReturn(run func(ctx context.Context, password string) (string, error)) *Hasher_Hash_Call {
	_c.Call.Return(run)
	return _c
}
