name: srv-ci

on:
  push:
    branches-ignore:
      - master
    paths:
      - 'apps/srv/**'

jobs:
  lint:
    uses: ./.github/workflows/srv.lint.yaml
    with:
      working_directory: './apps/srv'
  test:
    uses: ./.github/workflows/srv.test.yaml
    with:
      working_directory: './apps/srv'
