name: web-cd

on:
  push:
    branches:
      - master
    tags:
      - v*
    paths:
      - 'apps/web/**'

jobs:
  fmt:
    uses: ./.github/workflows/web.fmt.yaml
    with:
      working_directory: ./apps/web
  build:
    runs-on: ubuntu-latest
    needs: [ fmt ]
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata for docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}/web
          tags: |
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/master' }}
            type=semver,pattern={{version}},value={{tag}},enable=${{ startsWith(github.ref, 'refs/tags/v') }}
            type=sha,format=short
      - name: Build and push multi-platform Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./apps/web
          file: ./apps/web/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
